language: java
jdk:
- oraclejdk8
script: make test
branches:
  only:
  - master
services:
- mysql
before_install:

- mysql -e "USE guestbookdb;"
- mysql -e "CREATE TABLE 'guestbook'.'message' (  'idMessage' INT NOT NULL AUTO_INCREMENT,  'email' VARCHAR(45) NOT NULL,  'password' VARCHAR(45) NOT NULL,  'date' DATETIME NOT NULL,  'modifiedDate' DATETIME NOT NULL,  'text' VARCHAR(300) NOT NULL,  PRIMARY KEY ('idMessage'),  UNIQUE INDEX 'idMessage_UNIQUE' ('idMessage' ASC));"

